### ISSUE TITLE
Bower components are missing

### ISSUE THREAD

**Issue by minaketan-sabar** [Naman-Kumar-Sinha/red-crafts#6]
Bower components are missing like angular.js, etc. That does not come with angular seed project. Strange.

**Comment by Naman-Kumar-Sinha** [comment]
This was because the node was not installed properly on your machine. 

1. Uninstalled the node and the cache data from AppData/Roaming. 
2. Removed the local repository. 
3. Installed correct node package
4. Cloned red-crafts again from the master repository. 
5. Ran npm install and the devdependencies were loaded properly. 
6. Please note that bower components are installed as per specified in .bowerrc file package.json. 

Issue #6 is closed.

**Comment by Naman-Kumar-Sinha** [comment]
In addition, Bower components were missing in GIT. This created issue when tried to clone and run the project on other local env. So, as part of #11 commit, I've added removed bower components from GITIGNORE and included it in our GIT repository. However, in production, we must use the CDNs as much as possible.
